### PR TITLE
Fix path to config file

### PR DESCRIPTION
**Pull request by george-cz**
Hi,

This fixes the issue when you couldn't use `comment` command, because the editor didn't have the correct path to the config file.

### CODE REVIEW

**Comment by crisward** [comment]
Thanks!

**Comment by george-cz** [comment]
Sure, no problem :)

**Comment by crisward** [comment]
I've pushed the update to VSCode marketplace, so you should be able to update now. Seems to have fixed the commenting issue (not that you can use them everywhere in jsx)

**Comment by george-cz** [comment]
Haha cool :)

**Pull request merged**
